//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofos2.Sender.ColaTransactionSender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/spork-api/api/")]
        public string BASE_URL {
            get {
                return ((string)(this["BASE_URL"]));
            }
            set {
                this["BASE_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SIDC-1-2-1-3")]
        public string BRANCH_CODE {
            get {
                return ((string)(this["BRANCH_CODE"]));
            }
            set {
                this["BRANCH_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\DatawarehouseSyncher\\Dropsite")]
        public string DROPSITE_FOLDER {
            get {
                return ((string)(this["DROPSITE_FOLDER"]));
            }
            set {
                this["DROPSITE_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SIDCCOLA98XRT4MZ7YQK")]
        public string API_TOKEN {
            get {
                return ((string)(this["API_TOKEN"]));
            }
            set {
                this["API_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pos_upd_ca_cncl_dw.php")]
        public string API_CANCELCHARGEAMOUNT_URL {
            get {
                return ((string)(this["API_CANCELCHARGEAMOUNT_URL"]));
            }
            set {
                this["API_CANCELCHARGEAMOUNT_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pos_upd_ctrans_dw.php")]
        public string API_CANCELTRANSACTION_URL {
            get {
                return ((string)(this["API_CANCELTRANSACTION_URL"]));
            }
            set {
                this["API_CANCELTRANSACTION_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pos_upd_stub_dw.php")]
        public string API_COLASTUB_URL {
            get {
                return ((string)(this["API_COLASTUB_URL"]));
            }
            set {
                this["API_COLASTUB_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pos_ins_ctrans_dw.php")]
        public string API_COLA_URL {
            get {
                return ((string)(this["API_COLA_URL"]));
            }
            set {
                this["API_COLA_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string HOST {
            get {
                return ((string)(this["HOST"]));
            }
            set {
                this["HOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string DB_USERNAME {
            get {
                return ((string)(this["DB_USERNAME"]));
            }
            set {
                this["DB_USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c3VwZXJ2aXNvcg==")]
        public string DB_PASSWORD {
            get {
                return ((string)(this["DB_PASSWORD"]));
            }
            set {
                this["DB_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("main")]
        public string DB_NAME {
            get {
                return ((string)(this["DB_NAME"]));
            }
            set {
                this["DB_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pos_ins_ctrans_dw.php")]
        public string API_ACCOUNTING_URL {
            get {
                return ((string)(this["API_ACCOUNTING_URL"]));
            }
            set {
                this["API_ACCOUNTING_URL"] = value;
            }
        }
    }
}
